### ISSUE TITLE
Apply for using Twitter depressive symptoms dataset

### ISSUE THREAD

**Issue by LeiTong02** [halolimat/Social-media-Depression-Detector#1]
Hi Sir:
I am a research student of University of Leicester, UK and I am doing some research about depression detection via social media. As you mentioned in your ASONAM conference paper “Semi-Supervised Approach to Monitoring Clinical Depressive Symptoms in Social Media”, you have create a large Twitter depression dataset so can I apply for using your dataset? And I promise I just use it for researches and I will cite your publication in my paper

Many thanks.
Lei Tong

**Comment by halolimat** [comment]
Hi Charles,

Thanks for reaching out. We've made the lexicon available online with the code.
If you want the Twitter dataset please contact the first author of the paper if that is available for external use.

Best,
Hussein
